/*
 * To change this license header, choose License Headers in Project Properties.
 */
package Proyecto;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;

/**
 * @author Herzh
 */
public class pantalla extends javax.swing.JFrame implements KeyListener {

	int x;
	ArrayList<Bala> balas = new ArrayList<Bala>();
	public ArrayList<Enemigo> enemigos;//variable global

	public void disparar() {
		Bala bala = new Bala(this, this.nave1.getLocation().x);
		this.add(bala);
		this.repaint();
		balas.add(bala);
	}

	public void desaparecerBala(Bala bala) {
		this.remove(bala);
		this.repaint();
	}

	public pantalla() {
		initComponents();
		addKeyListener(this);
		setFocusable(true);
		setFocusTraversalKeysEnabled(false);

		x = 283;
		nave1.setLocation(x, 500);
		enemigos = new ArrayList<Enemigo>();

		ponerEnemigo();
	}

	public void ponerEnemigo() {
		Enemigo enemigo1 = new Enemigo(5, 10);
		Enemigo enemigo2 = new Enemigo(200, 10);
		Enemigo enemigo3 = new Enemigo(380, 10);
		Enemigo enemigo4 = new Enemigo(100, 100);
		Enemigo enemigo5 = new Enemigo(290, 100);
		Enemigo enemigo6 = new Enemigo(200, 180);

		this.add(enemigo1);
		this.add(enemigo2);
		this.add(enemigo3);
		this.add(enemigo4);
		this.add(enemigo5);
		this.add(enemigo6);

		this.repaint();//actualizar la pantalla

		enemigos.add(enemigo1);
		enemigos.add(enemigo2);
		enemigos.add(enemigo3);
		enemigos.add(enemigo4);
		enemigos.add(enemigo5);
		enemigos.add(enemigo6);
	}

	public void desaparecerEnemigo(int nEnemigo, Bala bala) {
		Enemigo m = (Enemigo) enemigos.get(nEnemigo);
		this.remove(m);
		this.remove(bala);
		this.repaint();
		enemigos.remove(nEnemigo);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nave1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        nave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/nave1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(nave1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addComponent(nave1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new pantalla().setVisible(true);
			}
		});
	}

	@Override
	public void keyTyped(KeyEvent e) {
		System.out.println("typed");
	}

	@Override
	public void keyPressed(KeyEvent e) {

		int key = e.getKeyCode();

		// Mover a la Izquierda
		if (key == 37 && x > 0) {
			x -= 10;
			nave1.setLocation(x, 506);
		}
		
		// Mover a la derecha
		if (key == 39 && x < 600 - 61) {
			x += 10;
			nave1.setLocation(x, 506);
		}

		if (key == 32) {
			disparar();
		}
	}

	@Override
	public void keyReleased(KeyEvent e) {

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nave1;
    // End of variables declaration//GEN-END:variables

}
